### ISSUE TITLE
How to add more information to a blog post

### ISSUE THREAD

**Issue by gsilano** [bitcraze/bitcraze-website#109]
Hi there! Recently an article about ROS/Gazebo simulators for Crazyflie appeared on the blog pages (https://www.bitcraze.io/2021/12/simulation-possibilities/), and there my work (CrazyS) was mentioned. I would like to add more info such as the chapter of a book (following the mentioned conference article, https://github.com/gsilano/CrazyS/wiki/Publications) that we have published. In addition, the work I am doing (https://github.com/gsilano/CrazyS/pulls) to make the tool compatible with Neotic, etc.

Can you help me with this?

**Comment by knmcguire** [comment]
Hi! Yeah ofcourse! The blogs itself is embedded from wordpress so you can't find the source here. 

I indeed missed the pull request because the last time I tried CrazyS it was 3 weeks ago, just before this PR was started. But I should have double checked, sorry about that!

How about I change it to:

'CrazyS is based on the RotorS simulation with some additional off-board crazyflie controllers for position control. I wasn’t able to build it for my Ubuntu 20.04 just yet myself, but that there is [ongoing work ](https://github.com/gsilano/CrazyS/pull/89) to port CrazyS to ROS Noetic.  For me on a virtual machine with ROS melodic it build just fine! Note My laptop did had to work quite hard when I wanted to simulate more than 1 Crazyflie, but the physics and plugins that were made for Gazebo is enabling many to do a lot for their research. Please check out [the core papers](https://github.com/gsilano/CrazyS/wiki/Publications) about CrazyS! '

**Comment by gsilano** [comment]
Great! Thanks!! :blush:

**Comment by knmcguire** [comment]
It has been updated ! https://www.bitcraze.io/2021/12/simulation-possibilities/
